apiVersion: batch/v1
kind: CronJob
metadata:
  name: lollipop-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template: 
        spec:
          containers:
          - name: lollipop-cron
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Welcome to K8S-pancake study lab!; sleep 30
          restartPolicy: OnFailure
