apiVersion: batch/v1
kind: CronJob
metadata:
  name: lollipop-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template: 
        spec:
          containers:
          - name: lollipop-cron
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Bem Vindo ao K8S-pancake; sleep 30
          restartPolicy: OnFailure
