apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: primeiro-deploy-simples
  name: primeiro-deploy-simples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primeiro-deploy-simples
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: primeiro-deploy-simples
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
