apiVersion: v1
kind: Pod
metadata:
  name: podinho-storage-ef
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: storage-ef
      mountPath: /data/podinho-storage-ef
  volumes:
  - name: storage-ef
    emptyDir: {}

