apiVersion: v1
kind: Pod
metadata:
  name: pod-simples
  labels:
    run: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
