apiVersion: v1
kind: Pod
metadata:
  name: pod-simples-com-svc
  labels:
    run: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    ports:
    - containerPort: 80
