apiVersion: v1
kind: Pod
metadata: 
  name: pod-para-service
  labels:
    app: pod-para-service
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    ports: 
    - containerPort: 80



