apiVersion: v1
kind: Service
metadata: 
  name: service-para-pod
  labels:
    app: pod-para-service
spec:
  selector:
    app: pod-para-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
