apiVersion: v1
kind: PersistentVolume
metadata:
  name: 04-pv-hostpath
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    server: 172.31.76.73
    readOnly: false  
