apiVersion: v1
kind: Pod
metadata:
  name: 04-pod-hostpath-test
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: 04-pod-hostpath-test
    volumeMounts:
    - mountPath: /hostpath-test
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /opt/dados
      # path example 
      # path: /var/lib/docker
      # type: Directory
