apiVersion: v1
kind: Pod
metadata:
  name: 11-pod-with-secret-file
spec:
  containers:
  - name: 11-pod-with-secret-file
    image: redis
    volumeMounts:
    - name: pancake
      mountPath: "/etc/pancake"
      readOnly: true
  volumes:
  - name: pancake
    secret:
      secretName: 11-secret-new    
