apiVersion: v1
kind: Pod
metadata:
  name: 11-pod-new
spec:
  containers:
  - name: container-new
    image: k8s.gcr.io/busybox
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - secretRef: 
        name: 11-secret-new
  restartPolicy: Never
