apiVersion: v1
kind: Pod
metadata:
  name: 11-pod-with-secret-env
spec:
  containers:
  - name: container-with-secret-env
    image: redis
    #command: ["/bin/sh","-c","env"]
    #envFrom:
    #- secretRef:
    #name: 11-secret-new
    env:
      - name: SECRET_USER
        valueFrom:
          secretKeyRef:
            name: 11-secret-new
            key: user
      - name: SECRET_PASS
        valueFrom:
          secretKeyRef:
            name: 11-secret-new
            key: pass
  restartPolicy: Never
