apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    resources: {}
    ports:
    - containerPort: 80
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
