apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-v2
spec:
  selector:
    matchLabels:
      app: giropops
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 5
  template:
    metadata:
      labels:
        app: giropops
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: giropops
        image: linuxtips/nginx-prometheus-exporter:1.0.0
        env:
        - name: VERSION
          value: "1.0.0"
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
        - containerPort: 32111
