apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-prometheus-alertmanager
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/alertmanager
    server: 172.31.76.73   
    readOnly: false    
