apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-prometheus-server
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/prometheus
    server: 172.31.76.73 
    readOnly: false    
